[package]
name = "revoltbotcurl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.8.5"

# websocket
url="*"
tungstenite = { version = "0.17.3", features = ["native-tls"] }

# JSON
ajson = "0.2.4"
serde_json="*"
serde = { version = "1.0", features = ["derive"] }
